global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: [ "host.docker.internal:9090" ]

  - job_name: "grafana"
    static_configs:
      - targets: [ 'host.docker.internal:3000' ]

  - job_name: "cosmeticsshop_api"
    metrics_path: /metrics-text
    static_configs:
      - targets: [ 'host.docker.internal:15001' ]
